package yagen.waitmydawn.checker.core;

import org.junit.jupiter.api.Test;

import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * mods.toml 解析：**两种写法都要认**。
 *
 * <p>2026-09-26 实测（万象包）：{@code panda-temple-V1-1.21+.jar} 用的是内联数组写法，
 * 旧实现只认 {@code [[mods]]} 表头 → 整个模组读不到 → ① 静态预检把它当"没装"（依赖它的模组被误判缺前置）
 * ② 拿不到声明版本，`Empty pre-release` 就没法反查肇事模组。
 */
class ModTomlTest {

    /** 实测原文（从 panda-temple-V1-1.21+.jar 的 META-INF/neoforge.mods.toml 里抄下来的） */
    private static final String INLINE_ARRAY = """

            modLoader = 'javafml'
            loaderVersion = '[1,)'
            license = 'MIT'
            showAsResourcePack = false
            mods = [
            	{ modId = 'mr_panda_temple', version = '1-V1-1.21+', displayName = 'Panda Temple', description = 'Spawns a mysterious overgrown temple in the jungle inhabited by our favorite bamboo eating creature!', logoFile = 'panda-temple_pack.png', updateJSONURL = 'https://api.modrinth.com/updates/z0qJSbtP/forge_updates.json?neoforge=only', credits = 'Generated by Modrinth', authors = 'dark_phoenix_', displayURL = 'https://modrinth.com/datapack/panda-temple' },
            ]
            issueTrackerURL = 'https://discord.gg/YPgxKKb2Mr'
            """;

    @Test
    void 内联数组写法的mods也要读出来() {
        List<ModToml.ModDecl> mods = ModToml.mods(INLINE_ARRAY);

        assertEquals(1, mods.size(), "内联数组里那一个模组必须被读出来");
        assertEquals("mr_panda_temple", mods.get(0).modId());
        assertEquals("1-V1-1.21+", mods.get(0).version(), "声明版本要原样保留（L4 归因靠它反查）");
    }

    @Test
    void 表头写法的mods与dependencies仍然照常解析() {
        String toml = """
                [[mods]]
                modId = "ars_nouveau"
                version = "5.13.1"

                [[dependencies.ars_nouveau]]
                modId = "neoforge"
                versionRange = "[21.1.247,)"
                type = "required"

                [[dependencies.ars_nouveau]]
                modId = "geckolib"
                versionRange = "${file.jarVersion}"
                type = "required"
                """;

        List<ModToml.ModDecl> mods = ModToml.mods(toml);
        assertEquals(List.of("ars_nouveau"), mods.stream().map(ModToml.ModDecl::modId).toList());
        assertEquals("5.13.1", mods.get(0).version());

        List<ModToml.DepDecl> deps = ModToml.deps(toml);
        assertEquals(2, deps.size());
        assertEquals("neoforge", deps.get(0).target());
        assertEquals("[21.1.247,)", deps.get(0).versionRange());
        assertTrue(deps.get(1).placeholder(), "${...} 占位符要单独标出来");
        assertEquals("*", deps.get(1).versionRange(), "占位符不能当成真实区间参与判定");
    }

    @Test
    void 值里出现类似键值对的文本不能被当成键() {
        // description 里写了 "version = '9.9.9'"：不能把 description 里的内容当模组版本
        String toml = """
                mods = [
                	{ modId = 'demo', version = '1.0.0', description = "trick: version = '9.9.9'" },
                ]
                """;

        List<ModToml.ModDecl> mods = ModToml.mods(toml);
        assertEquals(1, mods.size());
        assertEquals("demo", mods.get(0).modId());
        assertEquals("1.0.0", mods.get(0).version(), "键必须在引号外才算，值里的文本不算");
    }

    @Test
    void 内联数组里多个条目都要读到() {
        String toml = """
                mods = [
                	{ modId = 'aaa', version = '1.0' },
                	{ modId = 'bbb', version = '2.0' },
                ]
                """;

        List<ModToml.ModDecl> mods = ModToml.mods(toml);
        assertEquals(List.of("aaa", "bbb"), mods.stream().map(ModToml.ModDecl::modId).toList());
        assertEquals(List.of("1.0", "2.0"), mods.stream().map(ModToml.ModDecl::version).toList());
    }
}
